namespace SystemAudioAnalyzer.App.Localization;

/// <summary>Every user-visible text, English and Russian. Units always go in parentheses: "Label (unit):".</summary>
internal static class Strings
{
    public static readonly IReadOnlyDictionary<string, (string English, string Russian)> Table = new Dictionary<string, (string, string)>
    {
        // Main window
        ["SourceLabel"] = ("SOURCE", "ИСТОЧНИК"),
        ["Device"] = ("Device", "Устройство"),
        ["Stream"] = ("Stream", "Поток"),
        ["Start"] = ("START", "СТАРТ"),
        ["Stop"] = ("STOP", "СТОП"),
        ["Clear"] = ("Clear", "Очистить"),
        ["ClearTip"] = ("Clear the URL history", "Очистить историю адресов"),
        ["UrlTip"] = ("Stream URL; the list holds the last 60 opened", "Адрес потока; в списке — последние 60 открытых"),
        ["Reset"] = ("RESET", "СБРОС"),
        ["Png"] = ("PNG", "PNG"),
        ["SettingsButton"] = ("SETTINGS", "НАСТРОЙКИ"),
        ["Tab_Waterfall"] = ("Waterfall", "Водопад"),
        ["Tab_Loudness"] = ("Loudness", "Громкость"),
        ["Tab_Rta"] = ("RTA", "RTA"),
        ["Tab_Phase"] = ("Phase", "Фаза"),
        ["Tab_Analyzer"] = ("Analyzer", "Анализатор"),
        ["Tab_Meters"] = ("Meters", "Индикаторы"),
        ["Momentary"] = ("Momentary", "Мгновенная"),
        ["ShortTerm"] = ("Short-term", "Кратковременная"),
        ["Integrated"] = ("Integrated", "Интегральная"),
        ["Win1m"] = ("1m", "1 мин"),
        ["Win2m"] = ("2m", "2 мин"),
        ["Win3m"] = ("3m", "3 мин"),
        ["Win5m"] = ("5m", "5 мин"),
        ["Win10m"] = ("10m", "10 мин"),
        ["Win20m"] = ("20m", "20 мин"),
        ["Win30m"] = ("30m", "30 мин"),
        ["Win1h"] = ("1h", "1 ч"),
        ["Win6h"] = ("6h", "6 ч"),
        ["Win12h"] = ("12h", "12 ч"),
        ["Mono"] = ("Mono", "Моно"),
        ["TiltTip"] = ("RTA tilt: 0 = real levels, +3 dB/oct = flat for pink noise", "Наклон RTA: 0 — реальные уровни, +3 дБ/окт — ровная картинка для розового шума"),
        ["Tgt"] = ("Tgt", "Цель"),
        ["Avg"] = ("Avg", "Сред."),
        ["Tilt"] = ("Tilt", "Накл."),
        ["ScaleAuto"] = ("auto", "авто"),

        // Status bar and messages
        ["StatusReady"] = ("Ready.", "Готов к анализу."),
        ["ValidationUrl"] = ("Enter a valid HTTP/HTTPS address of an Icecast or HLS stream.", "Введите корректный HTTP/HTTPS адрес Icecast или HLS-потока."),
        ["StatusReset"] = ("Measurements reset.", "Измерения сброшены."),
        ["StatusStarting"] = ("Starting analysis…", "Запуск анализа…"),
        ["StatusConnectingHost"] = ("Connecting to {0}…", "Подключение к {0}…"),
        ["StatusRunning"] = ("Analysis is running.", "Анализ выполняется."),
        ["StatusStartFailed"] = ("Could not start the analysis: {0}", "Не удалось запустить анализ: {0}"),
        ["StatusStopped"] = ("Analysis stopped.", "Анализ остановлен."),
        ["StatusStopFailed"] = ("Could not stop the analysis: {0}", "Не удалось остановить анализ: {0}"),
        ["StatusConnecting"] = ("Connecting to the source…", "Подключение к источнику…"),
        ["StatusBuffering"] = ("Buffering the stream…", "Буферизация потока…"),
        ["StatusBufferingPercent"] = ("Buffering the stream… {0}%", "Буферизация потока… {0}%"),
        ["StatusSourceFault"] = ("Source error. You can start again.", "Ошибка источника. Можно повторить запуск."),
        ["Diagnostics"] = ("{0} fps · delay {1} ms · UI {2} ms · dropped buffers {3}", "{0} fps · доставка {1} мс · UI {2} мс · потеряно буферов {3}"),
        ["ConfirmDiscardText"] = ("Discard the unsaved changes and switch profile?", "Отбросить несохранённые изменения и сменить профиль?"),
        ["ConfirmDiscardTitle"] = ("Unsaved changes", "Несохранённые изменения"),
        ["SaveProfileFailed"] = ("Unable to save the profile. Check access to the application's Data folder.", "Не удалось сохранить профиль. Проверьте доступ к папке Data приложения."),

        // Drawn on the instruments
        ["RailMax"] = ("MAX", "МАКС"),
        ["RailNow"] = ("NOW", "ТЕК"),
        ["CaptionMomentary"] = ("Momentary Loudness", "Мгновенная громкость"),
        ["CaptionShortTerm"] = ("Short-term Loudness", "Кратковременная громкость"),
        ["CaptionIntegrated"] = ("Integrated Loudness", "Интегральная громкость"),
        ["TargetLabel"] = ("Target {0} LU", "Цель {0} LU"),
        ["UnitHz"] = ("Hz", "Гц"),
        ["UnitKhz"] = ("kHz", "кГц"),

        // Settings window
        ["SettingsTitle"] = ("Settings", "Настройки"),
        ["Language"] = ("Language:", "Язык:"),
        ["Preset"] = ("Preset:", "Профиль:"),
        ["SaveAs"] = ("Save as:", "Сохранить как:"),
        ["Save"] = ("Save", "Сохранить"),
        ["Delete"] = ("Delete", "Удалить"),
        ["Add"] = ("Add", "Добавить"),
        ["ColorButton"] = ("Color…", "Цвет…"),
        ["MakeDefault"] = ("Make the selected preset the default for new panels", "Сделать выбранный профиль профилем по умолчанию"),
        ["DefaultSuffix"] = (" (default)", " (по умолчанию)"),
        ["Apply"] = ("Apply", "Применить"),
        ["Ok"] = ("OK", "OK"),
        ["Cancel"] = ("Cancel", "Отмена"),
        ["FftSize"] = ("FFT size (samples):", "Размер FFT (отсчётов):"),
        ["Window"] = ("Window:", "Окно:"),
        ["LogFrequency"] = ("Logarithmic frequency scale", "Логарифмическая шкала частот"),
        ["LogAmplitude"] = ("Logarithmic amplitude scale", "Логарифмическая шкала амплитуд"),
        ["MinLevel"] = ("Min level (dB):", "Минимальный уровень (дБ):"),
        ["Gain"] = ("Gain (×):", "Усиление (×):"),
        ["CursorColor"] = ("Cursor color:", "Цвет курсора:"),
        ["TextColor"] = ("Text color:", "Цвет текста:"),
        ["DisplayFloor"] = ("Display floor (dB):", "Нижний порог (дБ):"),
        ["DisplayOffset"] = ("Display offset (dB):", "Смещение (дБ):"),
        ["GradientDb"] = ("Gradient stops (dB):", "Пороги градиента (дБ):"),
        ["StopLevelDb"] = ("Level (dB):", "Уровень (дБ):"),
        ["StopLevelLufs"] = ("Level (LUFS):", "Уровень (LUFS):"),
        ["UnitDb"] = (" dB", " дБ"),
        ["UnitLufs"] = (" LUFS", " LUFS"),
        ["Attack"] = ("Attack (ms):", "Атака (мс):"),
        ["Release"] = ("Release (ms):", "Спад (мс):"),
        ["PeakHold"] = ("Peak hold (ms):", "Удержание пика (мс):"),
        ["MeterRange"] = ("Peak/RMS range (dB):", "Диапазон Peak/RMS (дБ):"),
        ["ShowClip"] = ("Show clip indicator and peak readout", "Показывать индикатор клиппинга и значения пиков"),
        ["NoRms"] = ("Disable RMS bar (L/R)", "Отключить RMS-полосу (L/R)"),
        ["ShowDbScale"] = ("Show dB scale (L/R)", "Показывать шкалу дБ (L/R)"),
        ["ShowLufsIndicator"] = ("Show LUFS indicator", "Показывать индикатор LUFS"),
        ["LufsBarShows"] = ("LUFS bar shows:", "Индикатор LUFS показывает:"),
        ["IntegratedWindow"] = ("Integrated window (s):", "Окно Integrated (с):"),
        ["ShowLkfs"] = ("Show LKFS readout", "Показывать значение LKFS"),
        ["FontSize"] = ("UI font size:", "Размер шрифта:"),
        ["LufsScale"] = ("LUFS scale:", "Шкала LUFS:"),
        ["LufsScaleParameters"] = ("Scale top / bottom / step (LU):", "Шкала: верх / низ / шаг (LU):"),
        ["PeakColor"] = ("Peak color:", "Цвет пика:"),
        ["RmsColor"] = ("RMS color:", "Цвет RMS:"),
        ["LufsColor"] = ("LUFS color:", "Цвет LUFS:"),
        ["ClipColor"] = ("Clip color:", "Цвет клиппинга:"),
        ["MeterColorCompat"] = ("Meter color (compatibility):", "Цвет индикатора (совместимость):"),
        ["OverloadColorCompat"] = ("Overload color (compatibility):", "Цвет перегрузки (совместимость):"),
        ["LoudnessWindow"] = ("Window (15–43200 s):", "Окно (15–43200 с):"),
        ["Mode"] = ("Mode:", "Режим:"),
        ["YSpan"] = ("Y span (LU):", "Диапазон по Y (LU):"),
        ["YCenter"] = ("Y center (LUFS):", "Центр по Y (LUFS):"),
        ["TargetLine"] = ("Target line (LU):", "Целевая линия (LU):"),
        ["TargetRangeLu"] = ("Target range (± LU):", "Допуск цели (± LU):"),
        ["ColorGradientLufs"] = ("Color gradient stops (LUFS):", "Пороги цветового градиента (LUFS):"),
        ["SaveRuntime"] = ("Save current settings from program window as default", "Сохранить текущие настройки окна программы как профиль по умолчанию"),
        ["Source"] = ("Source:", "Источник:"),
        ["Resolution"] = ("Resolution:", "Разрешение:"),
        ["Averaging"] = ("Averaging (1–1000):", "Усреднение (1–1000):"),
        ["TiltLabel"] = ("Tilt (dB/oct):", "Наклон (дБ/окт):"),
        ["TiltHelp"] = ("0 = real levels; +3 = compensates a 3 dB/oct roll-off around 1 kHz, so pink noise looks flat.", "0 — реальные уровни; +3 — компенсация спада 3 дБ/окт относительно 1 кГц, розовый шум выглядит ровным."),
        ["RtaRelease"] = ("Release (dB/s):", "Спад (дБ/с):"),
        ["ScaleTop"] = ("Scale top (dB):", "Верх шкалы (дБ):"),
        ["ScaleRange"] = ("Scale range (dB):", "Диапазон шкалы (дБ):"),
        ["RtaTargetLine"] = ("Target line (dB):", "Целевая линия (дБ):"),
        ["RtaTargetRange"] = ("Target range (± dB):", "Допуск цели (± дБ):"),
        ["ShowCaps"] = ("Show peak hold caps", "Показывать маркеры удержания пика"),
        ["BarColor"] = ("Bar color:", "Цвет полос:"),
        ["PeakCapColor"] = ("Peak cap color:", "Цвет маркера пика:"),
        ["TargetBandColor"] = ("Target band color:", "Цвет полосы цели:"),
        ["GainCompensation"] = ("Gain compensation", "Компенсация усиления"),
        ["GainValue"] = ("Gain (×): ", "Усиление (×): "),

        // Option lists
        ["RtaMono"] = ("Mono (L+R)", "Моно (L+R)"),
        ["Oct1"] = ("1/1 octave", "1/1 октавы"),
        ["Oct3"] = ("1/3 octave", "1/3 октавы"),
        ["Oct6"] = ("1/6 octave", "1/6 октавы"),
        ["Oct12"] = ("1/12 octave", "1/12 октавы"),
        ["Small"] = ("Small", "Мелкий"),
        ["Medium"] = ("Medium", "Средний"),
        ["Large"] = ("Large", "Крупный"),
        ["ScaleBroadcast"] = ("Broadcast (0…-36, step 3)", "Вещание (0…-36, шаг 3)"),
        ["ScaleFull"] = ("Full scale (0…-60, step 6)", "Полная шкала (0…-60, шаг 6)"),
        ["ScaleCustom"] = ("Custom", "Своя"),
    };
}
