<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>AAAnalyzer</AssemblyName>
    <ApplicationIcon>..\SystemAudioAnalyzer.Diagnostic\Assets\AAAnalyzer.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SystemAudioAnalyzer.Core\SystemAudioAnalyzer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
  </ItemGroup>
  <Target Name="CreateAppDataDirectory" AfterTargets="Build;Publish">
    <MakeDir Directories="$(OutDir)Data" Condition="'$(OutDir)' != ''" />
    <MakeDir Directories="$(PublishDir)Data" Condition="'$(PublishDir)' != ''" />
  </Target>
</Project>
